name: charge_sound
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  logger: ^2.4.0
  win32: ^5.5.4
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
